### ISSUE TITLE
t/prereq.t may fail

### ISSUE THREAD

**Issue by eserte** [briandfoy/brick#5]
On some systems t/prereq.t fails --- maybe even always if Test::Prereq is actually installed?
A sample fail report at CPAN Testers:
http://www.cpantesters.org/cpan/report/7fdfccc0-577c-11e8-8649-9a118c28008b

**Comment by briandfoy** [comment]
Yeah, Test::Prereq was a fragile way to do things and I don't do that anymore. Thanks,
